# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: name-tests-test
      - id: no-commit-to-branch
        args: [--branch, master]
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.11
    hooks:
      # Update the uv lockfile
      - id: uv-lock
      # Export uv.lock dependencies to requirements.txt
      - id: uv-export
      - id: uv-export
        args: [--no-dev, -o, requirements-prod.txt]
      - id: uv-export
        args: [--only-dev, --no-hashes, -o, requirements-dev.txt]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [--config, pyproject.toml]
      # Run the formatter.
      - id: ruff-format
        args: [--config, pyproject.toml]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.14.0"
    hooks:
      - id: mypy
        args: [--config-file, pyproject.toml]
  - repo: https://github.com/PyCQA/bandit
    rev: "1.8.0"
    hooks:
      - id: bandit
        args: [--configfile, pyproject.toml]
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'trufflehog git file://. --since-commit HEAD --results=verified,unknown --fail --no-update'
        language: system
        stages: ["pre-commit", "pre-push"]
  - repo: local
    hooks:
      - id: pytest
        name: PyTest
        entry: ./.venv/bin/pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
